In [1]:
import numpy as np

In [2]:
a = np.random.rand(3,5)

In [3]:
b = np.random.rand(5,3)

In [4]:
a

array([[0.04315346, 0.30098278, 0.76720154, 0.4611716 , 0.86912095],
       [0.07610731, 0.49650617, 0.27404984, 0.64253347, 0.0421158 ],
       [0.4989021 , 0.05974182, 0.82172882, 0.07163782, 0.9368119 ]])

In [5]:
b

array([[0.48003097, 0.03410149, 0.6144686 ],
       [0.42506294, 0.37445842, 0.95336057],
       [0.27286505, 0.18760146, 0.44871629],
       [0.3239482 , 0.29177886, 0.49523347],
       [0.51144213, 0.59185748, 0.54017471]])

In [6]:
np.dot(a,b)#умножение матриц

array([[0.95189488, 0.90706111, 1.35558215],
       [0.55204622, 0.45233268, 0.98403956],
       [0.99143558, 0.76890319, 1.27375781]])

In [7]:
c = np.array([1,2,3])

In [8]:
d = np.array([4,5,6])

In [9]:
np.inner(c,d)#1*4+2*5+3*6 скалярное умножение

32

In [10]:
np.outer(c,d)#1*4,1*5,1*6; 2*4,2*5,2*6; 3*4,3*5,3*6 дикартово произведение

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

In [11]:
np.trace(a)#след матрицы

1.3613884549610167

In [15]:
e = np.random.rand(3,3)#определитель матрицы
np.linalg.det(e)

-0.058160699419319936

In [16]:
np.linalg.eig(e)#возвращает собственные числа

(array([ 1.39338974, -0.20763992,  0.20102319]),
 array([[ 0.39177897,  0.82687763, -0.01022316],
        [ 0.32857611, -0.12903472, -0.49564812],
        [ 0.85938756, -0.54737868,  0.86846326]]))

In [17]:
np.linalg.solve(e,c)#матричные уравнения

array([ 4.23462332,  3.22349747, -4.22497902])

In [ ]:
#ЛОГИЧЕСКИЕ ФУНКЦИИ

In [19]:
a = np.array([[1,2,3,np.nan],[4,np.inf,5,np.NINF]])

In [20]:
np.all(a)#все ли значения истины

True

In [22]:
np.any(a)#имеются ли истинные значения

True

In [24]:
c = np.isnan(a)
c

array([[False, False, False,  True],
       [False, False, False, False]])

In [25]:
b = a.copy()

In [26]:
a==b #сравнение массивов

array([[ True,  True,  True, False],
       [ True,  True,  True,  True]])

In [29]:
a = [1,2,3,4,5,6,7,8]

In [31]:
np.random.choice(a,size = (2,3,5))#создает массив из указаного массива выбрав данные рандомно

array([[[7, 2, 2, 8, 4],
        [1, 5, 8, 3, 1],
        [4, 2, 2, 7, 3]],

       [[8, 4, 5, 7, 6],
        [1, 5, 2, 5, 8],
        [8, 6, 5, 7, 8]]])

In [32]:
b = np.array([2,3,4,5,6,7,8,9])

In [35]:
np.random.shuffle(b)#рандомнон перемешивает массив
b

array([9, 4, 8, 6, 3, 7, 2, 5])

In [36]:
np.random.sample()

0.7948869926426567

In [37]:
np.random.sample(5)#генерирует случайную выборку от0до1 из занного количества элементов

array([0.06762857, 0.42123718, 0.87451869, 0.77052042, 0.67730367])

In [38]:
np.random.normal(5,2.5,100)#генерирует стандартное распределение

array([6.07701736e+00, 5.33102113e+00, 4.75607638e+00, 5.96947972e+00,
       7.51980947e+00, 4.17978287e+00, 4.43336814e+00, 4.43422061e+00,
       3.45842532e+00, 3.89395167e+00, 5.64826354e+00, 1.08739504e-02,
       3.63776307e+00, 8.69156529e+00, 3.08699871e-01, 7.79873804e+00,
       3.34100553e+00, 6.74376978e+00, 1.06253847e+01, 4.57950824e+00,
       7.93257489e+00, 2.09526159e+00, 4.73307611e+00, 3.71879890e+00,
       5.02192668e-02, 4.52579829e+00, 7.02895086e+00, 9.30247776e+00,
       2.34760541e-01, 6.83814332e+00, 5.56437267e+00, 6.11066174e+00,
       3.21338601e+00, 4.11774019e+00, 4.47306468e+00, 2.76822263e+00,
       1.05690466e+00, 4.41454309e+00, 4.91956122e+00, 7.83716898e+00,
       8.86970914e+00, 5.71323823e+00, 2.33196591e+00, 6.81182385e+00,
       2.86809455e+00, 5.77608814e+00, 6.36342372e+00, 4.08910847e+00,
       1.09673023e+01, 8.17571038e+00, 2.86510970e+00, 7.07455995e+00,
       5.75607026e+00, 6.22968036e+00, 6.27114171e+00, 2.69179946e+00,
      

In [39]:
np.random.uniform(5,10,100)#генерирует равномерное распределение

array([8.54969667, 8.91634372, 6.3446106 , 7.81051362, 9.64025456,
       8.69962915, 7.61238585, 6.08468214, 7.51253946, 8.78813228,
       9.19262846, 9.37683094, 9.97469738, 6.8214149 , 9.48627863,
       6.39462482, 9.53479962, 8.00243802, 5.74980771, 7.25955586,
       6.02010252, 9.60114153, 5.10475508, 7.32684245, 9.75698726,
       5.60187293, 5.76114478, 9.99835931, 8.76632984, 7.9586159 ,
       5.03749447, 8.50278261, 7.62964722, 8.8763803 , 8.58886201,
       7.56388688, 5.04738033, 9.25135341, 7.84211018, 6.86081687,
       7.41928694, 5.72020432, 5.68663615, 9.54535202, 8.99682274,
       9.73020875, 5.67528782, 9.48320419, 6.36984339, 8.15932986,
       7.30955357, 8.77274148, 8.43469197, 5.05998506, 9.98470145,
       5.54244361, 5.40523189, 6.42552866, 7.74222952, 9.07705839,
       6.28509432, 5.44344398, 5.80449349, 7.52988129, 8.80530011,
       9.38383331, 7.76666981, 8.02993184, 5.74541313, 9.98741331,
       9.13973596, 9.79760764, 6.74861039, 9.29965145, 7.76474