In [1]:
import numpy as np

In [3]:
#создать одномерный массив
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [4]:
#тип данных
type(a)

numpy.ndarray

In [5]:
arr = [2,3,4,5,6,7,7,8,9,8]
a = np.array(arr)
a

array([2, 3, 4, 5, 6, 7, 7, 8, 9, 8])

In [6]:
a.shape
#показывает форму массива(количество элементов)

(5,)

In [7]:
a.ndim
#показывает размерность массива(одномерный,двумерный ...)

1

In [8]:
a.dtype
#показывает тип данных элементов массива

dtype('int32')

In [11]:
a = np.array(arr , dtype=np.float64)
a
#изменить тип данных в массиве

array([2., 3., 4., 5., 6., 7., 7., 8., 9., 8.])

In [17]:
a.astype(np.int32)

array([2, 3, 4, 5, 6, 7, 7, 8, 9, 8])

In [19]:
b = np.array([2,3,8,5,6,7,7,8,9,8])

In [20]:
a+b
#сложение массивов

array([ 4.,  6., 12., 10., 12., 14., 14., 16., 18., 16.])

In [21]:
a-b

array([ 0.,  0., -4.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [22]:
a*b

array([ 4.,  9., 32., 25., 36., 49., 49., 64., 81., 64.])

In [23]:
a/b

array([1. , 1. , 0.5, 1. , 1. , 1. , 1. , 1. , 1. , 1. ])

In [24]:
a**b

array([4.00000000e+00, 2.70000000e+01, 6.55360000e+04, 3.12500000e+03,
       4.66560000e+04, 8.23543000e+05, 8.23543000e+05, 1.67772160e+07,
       3.87420489e+08, 1.67772160e+07])

In [25]:
a%b

array([0., 0., 4., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
a.sum()
#агрегирование(сумма всех значений массива)

59.0

In [27]:
a.mean()#среднее значение

5.9

In [28]:
a.min()#миимальное значение

2.0

In [29]:
a.max()#максимальное значение 

9.0

In [36]:
#ДВУМЕРНЫЙ МАССИВ
arr2 = [[1,2,3,4,5],[1,2,3,4,5]]
b = np.array(arr2)
b

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [37]:
b.shape# 2 строки 5 столбцов

(2, 5)

In [38]:
c = np.array(arr2)
c

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [39]:
b+c

array([[ 2,  4,  6,  8, 10],
       [ 2,  4,  6,  8, 10]])

In [40]:
b.sum()

30

In [41]:
b.sum(axis=0)#ось 0 сумирует все элементы сверху вниз

array([ 2,  4,  6,  8, 10])

In [42]:
b.sum(axis=1)#слева направо сумирует

array([15, 15])

In [44]:
#МНОГОМЕРНЫЙ МАССИВ
arr3 =[ [[1,2,3,4],[1,2,3,4]],
        [[1,2,3,4],[1,2,3,4]],
        [[1,2,3,4],[1,2,3,4]]
    ]

In [45]:
d = np.array(arr3)
d

array([[[1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4]]])

In [46]:
d.shape#3 матрицы состоящие из 2 строк и 4 столбцов

(3, 2, 4)

In [47]:
d.sum(axis=0)

array([[ 3,  6,  9, 12],
       [ 3,  6,  9, 12]])

In [48]:
d.sum(axis=1)

array([[2, 4, 6, 8],
       [2, 4, 6, 8],
       [2, 4, 6, 8]])

In [49]:
d.sum(axis=2)

array([[10, 10],
       [10, 10],
       [10, 10]])

In [53]:
d.sum(axis=(0,1))#сложит все строки всех матриц в одну

array([ 6, 12, 18, 24])

In [55]:
np.eye(5,5)#возвращает единичный двумерный массив с указанным количеством строк и столбцов

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [56]:
np.empty((2,3,5))

array([[[1.27119194e-311, 1.02271589e-321, 0.00000000e+000,
         0.00000000e+000, 1.89146896e-307],
        [5.02034658e+175, 4.75183056e+174, 1.39586842e-075,
         1.71603893e+185, 8.00373719e+169],
        [4.04197529e-057, 4.26490461e-096, 1.12855837e+277,
         8.76730979e+252, 2.59027920e-144]],

       [[3.80985069e+180, 1.14428494e+243, 2.59027907e-144,
         7.79952704e-143, 9.30593567e+165],
        [6.18606075e+169, 8.03251318e-042, 3.80054680e+175,
         2.59027860e-144, 2.59903818e-144],
        [6.19410688e-091, 1.20143025e-071, 3.69847698e-057,
         1.11475752e+261, 1.16318408e-028]]])

In [57]:
np.zeros((1,2,3))#создает пустой массив с 0 значениями

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [58]:
np.full((2,3,5) ,fill_value=15)

array([[[15, 15, 15, 15, 15],
        [15, 15, 15, 15, 15],
        [15, 15, 15, 15, 15]],

       [[15, 15, 15, 15, 15],
        [15, 15, 15, 15, 15],
        [15, 15, 15, 15, 15]]])

In [59]:
np.ones((4,6,8))

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.,

In [60]:
np.ones_like(d)#создает массив на подобие введенного 

array([[[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [61]:
#создает дробный диапозон
np.arange(0 , 10 , 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [62]:
np.linspace(0 , 10 , 7)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

In [63]:
d

array([[[1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4]]])

In [64]:
#ИНДЕКСАЦИЯ МАССИВОВ
d[0]

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [65]:
d.shape#3 количество матриц 2 количество строк в каждой матрице 4 количество столбцов

(3, 2, 4)

In [67]:
d[1,1]

array([1, 2, 3, 4])

In [69]:
d[1,0,3]

4

In [70]:
d[1:, :1,2:]#СРЕЗ

array([[[3, 4]],

       [[3, 4]]])

In [72]:
f = d[0 , 1]
f

array([1, 2, 3, 4])

In [75]:
f[::-1]#переворачивает массив

array([4, 3, 2, 1])

In [77]:
f[::2]#выведет каждый второй элемент в массиве

array([1, 3])

In [78]:
f[1:4:2] = 100#заменила каждый 2-й элемент на 100
f

array([  1, 100,   3, 100])

In [79]:
h = f.copy()
h

array([  1, 100,   3, 100])

In [ ]:
#БРОАДКАСТИНГ(РАСШИРЕНИЕ МАССИВОВ)

In [80]:
x = np.array([1,2,3])
z = 5
x*z

array([ 5, 10, 15])

In [ ]:
#изменение формы массива

In [82]:
m = np.ones((3,5,4,1))

In [86]:
m.shape


(3, 5, 4, 1)

In [87]:
m.ndim

4

In [88]:
m.reshape(3,5,4)

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [89]:
m.reshape(3,5,2,2)

array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]])

In [90]:
np.resize(m , (3,4,4,2,1))

array([[[[[1.],
          [1.]],

         [[1.],
          [1.]],

         [[1.],
          [1.]],

         [[1.],
          [1.]]],


        [[[1.],
          [1.]],

         [[1.],
          [1.]],

         [[1.],
          [1.]],

         [[1.],
          [1.]]],


        [[[1.],
          [1.]],

         [[1.],
          [1.]],

         [[1.],
          [1.]],

         [[1.],
          [1.]]],


        [[[1.],
          [1.]],

         [[1.],
          [1.]],

         [[1.],
          [1.]],

         [[1.],
          [1.]]]],



       [[[[1.],
          [1.]],

         [[1.],
          [1.]],

         [[1.],
          [1.]],

         [[1.],
          [1.]]],


        [[[1.],
          [1.]],

         [[1.],
          [1.]],

         [[1.],
          [1.]],

         [[1.],
          [1.]]],


        [[[1.],
          [1.]],

         [[1.],
          [1.]],

         [[1.],
          [1.]],

         [[1.],
          [1.]]],


        [[[1.],
          [1.]],

In [94]:
a = np.ones((3,500,300))

In [ ]:
3*w*h

In [ ]:
1*kanal*1*w*1*h

In [ ]:
expand_dims()#расширяет массив

In [95]:
a.shape

(3, 500, 300)

In [98]:
b = np.expand_dims(a, axis=(0,2,4))

In [99]:
b.shape

(1, 3, 1, 500, 1, 300)

In [104]:
t = np.array([1,2,3])
t

array([1, 2, 3])

In [107]:
np.expand_dims(t,axis=(0, 2))

array([[[1],
        [2],
        [3]]])

In [ ]:
b.squeeze()#убирает оси с размерностью 1

In [110]:
b.squeeze(axis=(0,2)).shape

(3, 500, 1, 300)

In [115]:
b = b.squeeze().shape

In [116]:
np.pad(b, pad_width=(2, 3),constant_values=0)#добавляет указанные паддинги слева и справа

array([  0,   0,   3, 500, 300,   0,   0,   0])

In [121]:
c = np.ravel(a)#делает массив плоским или flatten()

In [122]:
c.shape

(450000,)

In [124]:
c.tolist()

[1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0

In [ ]:
#ПРЕОБРАЗОВАНИЕ МАССИВОВ

In [125]:
z = np.arange(9)
z

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [126]:
np.split(z,3)#разбивает массив на подмоссивы

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [127]:
np.split(z,[3,4,15])

[array([0, 1, 2]), array([3]), array([4, 5, 6, 7, 8]), array([], dtype=int32)]

In [130]:
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [131]:
np.insert(a, 3 ,1000 ,axis=1)#вставляет данные в массив

array([[   1.,    1.,    1., 1000.],
       [   1.,    1.,    1., 1000.]])

In [132]:
np.insert(a, (1,3) ,(1000,500) ,axis=1)

array([[   1., 1000.,    1.,    1.,  500.],
       [   1., 1000.,    1.,    1.,  500.]])

In [133]:
np.insert(a, (1,3) ,(1000,500))

array([   1., 1000.,    1.,    1.,  500.,    1.,    1.,    1.])

In [135]:
np.append(a,values=([100,200,300],[100,600,799]),axis=1)#вставляет данные в конец масива

array([[  1.,   1.,   1., 100., 200., 300.],
       [  1.,   1.,   1., 100., 600., 799.]])

In [136]:
np.append(a,values=([100,200,300],[100,600,799]))

array([  1.,   1.,   1.,   1.,   1.,   1., 100., 200., 300., 100., 600.,
       799.])

In [138]:
a = np.append(a,[[3,2,1]],axis=0)
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [3., 2., 1.],
       [3., 2., 1.]])

In [140]:
a = np.append(a,[[1],[1],[1],[1]],axis=1)
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [3., 2., 1., 1., 1.],
       [3., 2., 1., 1., 1.]])

In [141]:
np.unique(a)#возвращает уникальные значения в массиве

array([1., 2., 3.])

In [142]:
np.unique(a,axis=0)

array([[1., 1., 1., 1., 1.],
       [3., 2., 1., 1., 1.]])

In [143]:
np.unique(a,axis=1)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [145]:
els, ind = np.unique(a,axis=1, return_index=True)
els

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [146]:
ind

array([2, 1, 0], dtype=int64)

In [148]:
els, inv = np.unique(a,axis=1, return_inverse=True)
inv

array([2, 1, 0, 0, 0], dtype=int64)

In [149]:
els[inv]

array([[1., 2., 3.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [155]:
np.tile(a , 2)#копирует массив в него же

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [3., 2., 1., 1., 1., 3., 2., 1., 1., 1.],
       [3., 2., 1., 1., 1., 3., 2., 1., 1., 1.]])

In [157]:
np.tile(a , (2,1))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [3., 2., 1., 1., 1.],
       [3., 2., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [3., 2., 1., 1., 1.],
       [3., 2., 1., 1., 1.]])

In [158]:
np.repeat(a,2)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 3., 3., 2., 2., 1., 1., 1., 1., 1., 1., 3., 3., 2., 2.,
       1., 1., 1., 1., 1., 1.])

In [159]:
np.repeat(a,2,axis=0)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [3., 2., 1., 1., 1.],
       [3., 2., 1., 1., 1.],
       [3., 2., 1., 1., 1.],
       [3., 2., 1., 1., 1.]])

In [160]:
np.repeat(a,2,axis=1)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [3., 3., 2., 2., 1., 1., 1., 1., 1., 1.],
       [3., 3., 2., 2., 1., 1., 1., 1., 1., 1.]])

In [161]:
b = np.repeat(a,2,axis=1)


In [162]:
np.concatenate((a,b),axis=1)#обьеденяет массивы

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [3., 2., 1., 1., 1., 3., 3., 2., 2., 1., 1., 1., 1., 1., 1.],
       [3., 2., 1., 1., 1., 3., 3., 2., 2., 1., 1., 1., 1., 1., 1.]])

In [167]:
l = [[100,100,100],
     [100,100,100],
     [100,100,100]]
     

In [168]:
j = np.array(l)

In [169]:
x = [[200,200,200],
[200,200,200],
[200,200,200]]

In [170]:
k = np.array(x)

In [171]:
np.concatenate((j,k),axis=1)

array([[100, 100, 100, 200, 200, 200],
       [100, 100, 100, 200, 200, 200],
       [100, 100, 100, 200, 200, 200]])

In [172]:
np.concatenate((j,k),axis=0)

array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100],
       [200, 200, 200],
       [200, 200, 200],
       [200, 200, 200]])

In [174]:
np.hstack((j,k))

array([[100, 100, 100, 200, 200, 200],
       [100, 100, 100, 200, 200, 200],
       [100, 100, 100, 200, 200, 200]])

In [175]:
np.vstack((j,k))

array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100],
       [200, 200, 200],
       [200, 200, 200],
       [200, 200, 200]])

In [176]:
j.prod()#умножает все элементы массива

-1486618624

In [177]:
k.prod(axis=0)

array([8000000, 8000000, 8000000])

In [178]:
k.prod(axis=1)

array([8000000, 8000000, 8000000])

In [179]:
k.round(2)#округляет все элементы массива

array([[200, 200, 200],
       [200, 200, 200],
       [200, 200, 200]])

In [180]:
s = np.array([1,3,5,-7,8,6])

In [181]:
np.argmin(s)#возвращает индекс минимального значения в массиве

3

In [182]:
np.argmax(s)

4

In [184]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [185]:
np.diag(a)#возвращает главную диагональ матрицы

array([0, 4, 8])

In [186]:
np.diag(a, k=1)

array([1, 5])

In [ ]:
#ФИЛЬТРАЦИЯ ЭЛЕМЕНТОВ МАССИВА

In [193]:
a = np.arange(8).reshape(2,4)
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [194]:
np.where(a<4)

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))

In [195]:
np.where(a%2==1)

(array([0, 0, 1, 1], dtype=int64), array([1, 3, 1, 3], dtype=int64))

In [198]:
a[np.where(a%2==1)]#получаем массив из элемемнтов удовлетворяющих условию фильтрации


array([1, 3, 5, 7])

In [199]:
np.where((a%2==1)&(a>3))

(array([1, 1], dtype=int64), array([1, 3], dtype=int64))

In [202]:
a[np.where((a%2==1)&(a>3))]

array([5, 7])

In [203]:
a[np.where((a%2==1)|(a>3))]

array([1, 3, 4, 5, 6, 7])

In [205]:
np.where(a>3 ,a ,-1)#элементы со значением меньше 3 заменяем на -1

array([[-1, -1, -1, -1],
       [ 4,  5,  6,  7]])

In [ ]:
#СТАТИСТИКА В NUMPY

In [223]:
a = np.array([
    [
        [1,2,3],
        [4,10,7]
    ],
    [
        [101,13,28],
         [44,5,18] 
         ]
])

In [224]:
a

array([[[  1,   2,   3],
        [  4,  10,   7]],

       [[101,  13,  28],
        [ 44,   5,  18]]])

In [209]:
a.shape

(2, 2, 3)

In [210]:
a.ptp()#возвращает разницу между максимальным и минимальным значением элементов

100

In [211]:
a.ptp(axis=2)

array([[ 2,  6],
       [88, 39]])

In [212]:
a.ptp(axis=1)

array([[ 3,  8,  4],
       [57,  8, 10]])

In [221]:
a.ptp(axis=0)

99

In [226]:
np.percentile(a , 50 , axis=0)#находит указанный процентиль

array([[51. ,  7.5, 15.5],
       [24. ,  7.5, 12.5]])

In [225]:
a

array([[[  1,   2,   3],
        [  4,  10,   7]],

       [[101,  13,  28],
        [ 44,   5,  18]]])

In [227]:
np.percentile(a , 50 , axis=(1,2),method='closest_observation')

array([ 3, 18])

In [229]:
np.quantile(a , 0.5 , axis=(1,2),method='closest_observation')#считает квантильбтоже самое что процентиль только в процентах

array([ 3, 18])

In [230]:
np.median(a)#медиана

8.5

In [231]:
np.median(a, axis=(1,2))

array([ 3.5, 23. ])

In [232]:
np.average(a)#среднее

19.666666666666668

In [233]:
np.var(a)#разброс(отклонение от среднего)

748.0555555555553

In [234]:
np.std(a)#стандартное отклонение(корень из вариаций)

27.350604299641265

In [236]:
x = np.random.rand(3,3)#создаем рандомный массив
x

array([[0.76262191, 0.32999462, 0.3039979 ],
       [0.78102967, 0.82506164, 0.2990765 ],
       [0.6000511 , 0.6442711 , 0.61923589]])

In [237]:
np.corrcoef(x)#коффициент корреляции пирсена(строки переменные,измерения по столбцам)

array([[ 1.        ,  0.47815835, -0.79589328],
       [ 0.47815835,  1.        ,  0.15117628],
       [-0.79589328,  0.15117628,  1.        ]])

In [238]:
np.corrcoef(x, rowvar=False)#столбцы переменные ,вычесления в строках

array([[ 1.        , -0.06185293, -0.99687121],
       [-0.06185293,  1.        ,  0.14055108],
       [-0.99687121,  0.14055108,  1.        ]])

In [240]:
np.cov(x)#коверационная матрица

array([[ 0.06636303,  0.03594329, -0.00454642],
       [ 0.03594329,  0.08514634,  0.00097818],
       [-0.00454642,  0.00097818,  0.0004917 ]])

In [241]:
np.save('myFale.npy',x)#сохранить в файл

In [243]:
b = np.load('myFale.npy')#загрузить из файла
b

array([[0.76262191, 0.32999462, 0.3039979 ],
       [0.78102967, 0.82506164, 0.2990765 ],
       [0.6000511 , 0.6442711 , 0.61923589]])